./oscli cat nodes
./oscli cat health
./oscli cat cluster-info
./oscli cat disk
./oscli cat templates
./oscli cat indices
./oscli cat shards
./oscli cat recovery
./oscli cat master
./oscli cat field_data
./oscli cat alias
./oscli admin ls-role-mapping
./oscli admin ls-tenants
./oscli admin ls-security
